CREATE TABLE IF NOT EXISTS tki_ships (
  ship_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  ship_name varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  ship_destroyed varchar(1) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'N',
  character_name varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  recovery_time int(20) DEFAULT NULL,
  email varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  hull int(3) unsigned NOT NULL DEFAULT '0',
  `engines` int(3) unsigned NOT NULL DEFAULT '0',
  power int(3) unsigned NOT NULL DEFAULT '0',
  computer int(3) unsigned NOT NULL DEFAULT '0',
  sensors int(3) unsigned NOT NULL DEFAULT '0',
  beams int(3) unsigned NOT NULL DEFAULT '0',
  torp_launchers int(3) NOT NULL DEFAULT '0',
  torps int(20) NOT NULL DEFAULT '0',
  shields int(3) unsigned NOT NULL DEFAULT '0',
  armor int(3) unsigned NOT NULL DEFAULT '0',
  armor_pts int(20) NOT NULL DEFAULT '0',
  cloak int(3) unsigned NOT NULL DEFAULT '0',
  credits int(20) NOT NULL DEFAULT '0',
  sector int(10) unsigned NOT NULL DEFAULT '1',
  ship_ore int(20) NOT NULL DEFAULT '0',
  ship_organics int(20) NOT NULL DEFAULT '0',
  ship_goods int(20) NOT NULL DEFAULT '0',
  ship_energy int(20) NOT NULL DEFAULT '0',
  ship_colonists int(20) NOT NULL DEFAULT '0',
  ship_fighters int(20) NOT NULL DEFAULT '0',
  ship_damage int(5) NOT NULL DEFAULT '0',
  turns int(4) NOT NULL DEFAULT '0',
  on_planet varchar(1) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'N',
  dev_warpedit int(5) NOT NULL DEFAULT '0',
  dev_genesis int(5) NOT NULL DEFAULT '0',
  dev_beacon int(5) NOT NULL DEFAULT '0',
  dev_emerwarp int(5) NOT NULL DEFAULT '0',
  dev_escapepod varchar(1) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'N',
  dev_fuelscoop varchar(1) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'N',
  dev_minedeflector int(20) NOT NULL DEFAULT '0',
  turns_used int(10) unsigned NOT NULL DEFAULT '0',
  last_login datetime DEFAULT NULL,
  rating int(11) NOT NULL DEFAULT '0',
  score int(20) NOT NULL DEFAULT '0',
  team int(11) NOT NULL DEFAULT '0',
  team_invite int(11) NOT NULL DEFAULT '0',
  ip_address varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  planet_id int(10) unsigned NOT NULL DEFAULT '0',
  trade_colonists varchar(1) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Y',
  trade_fighters varchar(1) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'N',
  trade_torps varchar(1) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'N',
  trade_energy varchar(1) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Y',
  cleared_defenses varchar(99) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  lang varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'english.inc',
  dev_lssd varchar(1) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'N',
  PRIMARY KEY (ship_id),
  KEY tki_email (email),
  KEY tki_sector (sector),
  KEY tki_ship_destroyed (ship_destroyed),
  KEY tki_on_planet (on_planet),
  KEY tki_team (team)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=1 ;
