CREATE TABLE IF NOT EXISTS tki_planets (
  planet_id integer NOT NULL DEFAULT nextval('tki_planets_planet_id_seq'),
  sector_id integer NOT NULL DEFAULT '0',
  "name" character varying(15) DEFAULT NULL,
  organics integer NOT NULL DEFAULT '0',
  ore integer NOT NULL DEFAULT '0',
  goods integer NOT NULL DEFAULT '0',
  energy integer NOT NULL DEFAULT '0',
  colonists integer NOT NULL DEFAULT '0',
  credits integer NOT NULL DEFAULT '0',
  fighters integer NOT NULL DEFAULT '0',
  torps integer NOT NULL DEFAULT '0',
  "owner" integer NOT NULL DEFAULT '0',
  corp integer NOT NULL DEFAULT '0',
  base character varying(1) NOT NULL DEFAULT 'N',
  sells character varying(1) NOT NULL DEFAULT 'N',
  prod_organics integer NOT NULL DEFAULT '20',
  prod_ore integer NOT NULL DEFAULT '0',
  prod_goods integer NOT NULL DEFAULT '0',
  prod_energy integer NOT NULL DEFAULT '0',
  prod_fighters integer NOT NULL DEFAULT '0',
  prod_torp integer NOT NULL DEFAULT '0',
  defeated character varying(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (planet_id)
);
